// https://leetcode.com/problems/sum-game/discuss/1329380/One-liner
class Solution {
public:
    bool sumGame(string num) {
        int bal = 0, balq = 0;
        for (int i = 0; i < num.size(); ++i) {
            if (num[i] == '?')
                balq += (i < num.size() / 2 ? 1 : -1);
            else
                bal +=  (i < num.size() / 2 ? 1 : -1) * (num[i] - '0');
        }
        return balq & 1 || bal + balq * 9 / 2 != 0;  // if after balancing left and right question marks, still odd question marks on 1 side, then Alice must win.
       // Or if there are even number of question marks left, and if alice play optimally, the maximum number can be generated by 2 question marks is 9.
    }
};
